config/routes.rb
Rails.application.routes.draw do

  resources :join_table_order_items
  root 'items#index'
  resources :items do
  	resources :pics
  end
  resources :carts
  resources :orders
  resources :join_table_cart_items
  devise_for :users
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :join_table_cart_items
	has_many :items, through: :join_table_cart_items
	
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :join_table_cart_items
	has_many :carts, through: :join_table_cart_items
	has_many :join_table_order_items
	has_many :orders, through: :join_table_order_items
	validates :title, presence: true, length: { in: 3..14}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
    #validates :image_url, presence: true, format: {with: /\.(png|jpg|gif)\Z/i}
    has_one_attached :pic
end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
	belongs_to :item
	belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :join_table_order_items
	has_many :items, through: :join_table_order_items
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


	after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  has_many :items, through: :cart
  has_many :orders
  has_one :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
    def configure_permitted_paramters

        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :age])

        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :age,
        :email, :password])

    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show]
    before_action :authenticate_user!, exept: [:index, :show]
 
  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
    def sum
      sum = 0
        for i in (0..@cart.join_table_cart_items.length-1)
          sum = sum + @cart.join_table_cart_items[i].item.price
        end
      return sum 
    end
    @sum = sum
  end

  def new
  end

  def create
    @item = Item.find(params[:item_id])
    @join_table_cart_items = @cart.join_table_cart_item.new(item: item)
  end

  def update
  end

  def destroy
  end

  def edit
  
  end
  
  private

    def set_cart
      @cart = Cart.find_by(id: session[:cart_id]) || Cart.create
        session[:cart_id] ||= @cart.id
    end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

   def index
    @items = Item.all
    puts @items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "Description ajouté! maintenant upload votre cat_pic"
      redirect_to new_item_pic_path(@item.id)
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def edit
  end

  private
    def item_params
      params.require(:item).permit(
                  :title, 
                  :description,
                  :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
    
  end

  def new
  end

  def create

      # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to root_path
      

  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def new
  end

  def create
    @item = Item.find(params[:item_id])
    @item.pic.attach(params[:pic])
    redirect_to item_path(@item.id)
  end

  def index
  end

  def show
  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  after_create :UserMailer.welcome_email(self).deliver_now
 	def index
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :is_admin?, only: [:index]
	def show
		 @user = User.find(params[:id])
	end

	def index
		@order = Order.all
	end

	private
	def is_admin?
		if current_user.admin == true
			return true
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_table_cart_items_helper.rb
module JoinTableCartItemsHelper
end

app/helpers/join_table_order_items_helper.rb
module JoinTableOrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<h2> Panier </h2>
<ul>
	<% @cart.join_table_cart_items.each do |join| %>
	<li><%= join.item.title %></li>


	<strong>Ajouter le: <%= join.created_at%></strong>
	<li >Titre: "<%= join.item.title %>"</li> 
	<li>Description: "<%= join.item.description %>"</li> 
	<li>Prix: "<%= join.item.price %> $ "</li> 
	<li>Image_url :  "<%= join.item.image_url %>"</li>
	<%= link_to "Enlever du panier", join,  method: :delete, data: {confirm: "Etes-vous sûr"}, class: "btn btn-danger" %>
	<br>
	<br>
	<% end %>
</ul>
<br>
<strong> prix total à payer: <%= @sum %> $</strong><br>
<p ><%= link_to "Retour aux produits", root_path%></p>
	
	<%= form_tag join_table_order_items_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
    </label>
  </article>


          <script
            src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
           
            data-amount="<% @sum %>"
            data-currency="EUR"
            data-locale="auto"
            data-label="Passer la commande"></script>
   <% end %>

app/views/items/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- TITRE -->
    <title> CATTO
    </title>
    <!-- Important pour medias queries -->
    <meta content="initial-scale=1.0, width=device-width" name="viewport">
    <!-- Police de Caractère -->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  	<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- FEUILLES DE STYLE -->
    <link rel="stylesheet" href="assets/css/styles.css">
    <!-- scrollmagic -->
    <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/ScrollMagic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/plugins/debug.addIndicators.min.js"></script>
<body>
    <header>
        <h1>Because Cat is Awesome</h1>
         <h2>WELCOME TO CATTO</h2> 
    </header>
    <section>
        <div class="img1">
            <div class="box box1">
    </section>
    <section>
        <div class="img2">
            <div class="box box2">
    </section>

    <section>
        <div class="img3">
            <div class="box box3">
    </section>
    <script src="app.js"></script>
</body>

</html>
<h1>Bienvenue dans Catto</h1>
<%if user_signed_in?%>
<strong><%= link_to "Ajouter un nouveau Cat_pic", new_item_path %></strong><br>

  <!-- find if currend_user has a cart else it create a cart for the user -->
	<% cart = Cart.find_by(user_id:current_user.id)
		if !cart
			Cart.create(user_id:current_user.id)
		end	
	%>
	<a href="<%=cart_path(Cart.find_by(user_id:current_user.id ))%>">mon panier</a>
<%end%>
     <% @items.each do |item| %>
	     <p>Titre: "<%= item.title %>"</p> 
	     <p>Description: "<%= item.description %>"</p> 
	     <p>Prix: "<%= item.price %> $"</p> 
	     <% if item.pic.attached? == true%>
	     <img class="a" <%= image_tag item.pic, alt: 'pic' %>
	     <br>
	     <%end%>

	     <button> <%= link_to "afficher", item_path(item.id)%> </button>
	     <%if user_signed_in?%>
	     <button id='<%=item.id%>' class="add">ajout a mon panier</button>
	     <%end%>
	     <h3>=========================</h3>
     <%end%>

app/views/items/new.html.erb
<% if user_signed_in? %>

  <h1>Ajouter un nouveau cat_pic </h1>
  <strong>Inserer d'abord l'apropos de votre cat_pic</strong>

  <%= form_for @item do |f| %>

    <div class="field">
      <%= f.label :Titre %> 
      <%= f.text_field :title, autofocus: true, autocomplete: "title" %>
    </div>

     <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
    </div>

     <div class="field">
      <%= f.label :prix %>
      <%= f.number_field :price, autofocus: true, autocomplete: "price" %>
    </div>

    <div class="actions">
      <%= f.submit "Créer" %>
    </div>
  <% end %>

<% else %>
  <h1>Vous devez connecter pour pouvoir ajouter un photos</h1>
  <a href="<%= new_user_session_path %>" class="btn btn-outline-success my-2 my-sm-0" type="submit" >Se connecter</a>
  <a href="<%= new_user_registration_path %>" class="btn btn-outline-success my-2 my-sm-0" type="submit" >Créer un compte</a>
<%end%>

app/views/items/show.html.erb
<h1><%= @item.title %></h1>
	<p>Titre: "<%= @item.title %>"</p> 
	<p>Description: "<%= @item.description %>"</p> 
	<p>Prix: "<%= @item.price %> $ "</p> 
	<% if @item.pic.attached? == true%>
	    <img class="a" <%= image_tag @item.pic, alt: 'pic' %><br>
	<%end%>
<%if user_signed_in?%>
	    <button id='<%=@item.id%>' class="add">ajout a mon panier</button>
<%end%>

app/views/orders/create.html.erb
<h2>Thanks, you paid <strong><% @sum %></strong>!</h2>
<h1>Les Images Commandées</h1>
<% current_user.orders.each do |order|%>
	<% order.join_table_order_items.each do |join_item| %>
		<strong> commandé le <%= join_item.created_at %></strong>
		<p>Titre: "<%= join_item.item.title %>"</p> 
		<p>Description: "<%= join_item.item.description %>"</p> 
		<p>Prix: "<%= join_item.item.price %> $"</p> 
		<img src="<%= join_item.item.image_url %>"> <br>
		<br><br>
	<%end%>
<%end%>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

app/views/orders/show.html.erb
<strong>Vous avez belle et bien payé. Votre commande est passé, regardez votre mail.</strong><br>

<h1>Tout ce que vous avez commandé chez nous</h1>
<% current_user.orders.each do |order|%>
  <% order.join_table_order_items.each do |join_item| %>
    <strong> commandé le <%= join_item.created_at %></strong>
    <p>Titre: "<%= join_item.item.title %>"</p> 
    <p>Description: "<%= join_item.item.description %>"</p> 
    <p>Prix: "<%= join_item.item.price %> $"</p> 
    <img src="<%= join_item.item.image_url %>"> <br>
    <br><br>
  <%end%>
<%end%>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/users/index.html.erb
<h1>DASHBOARD ADMIN</h1>
		<table>
			<tr>
				<td><strong>Item_id</strong></td>
				<td><strong>Titre</strong></td>
				<td><strong>Prix</strong></td>
				<td><strong>Nombre d'achat</strong></td>
			</tr>
			<% @item_id = [] %>
			<% @order.each do |order| %>
				<% order.items.each do |item|%>
					<%@item_id << item.id %>
						<tr>
							<td><%= item.id %></td>
							<td><%= item.title %></td>
							<td><%= item.price %> $</td>
							<td><%= item.orders.count %></td>
						</tr>

				<% end %>
			<% end %>
			
		</table>

		<h1> nombre total des images vendus : <%= @item_id.count %></h1>

app/views/users/show.html.erb
email: <%= @user.email %><br><br>
first name :  <%= @user.first_name %><br><br>
last name:  <%= @user.last_name %><br><br>
description:   <%= @user.description %><br><br>
age:  <%= @user.age %>