config/routes.rb
Rails.application.routes.draw do

  resources :join_table_order_items
  root 'items#index'
  resources :items do
  	resources :pics
  end
  resources :carts
  resources :orders
  resources :join_table_cart_items
  devise_for :users
  resources :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :join_table_cart_items
	has_many :items, through: :join_table_cart_items
	
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :join_table_cart_items
	has_many :carts, through: :join_table_cart_items
	has_many :join_table_order_items
	has_many :orders, through: :join_table_order_items
	validates :title, presence: true, length: { in: 3..14}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
    #validates :image_url, presence: true, format: {with: /\.(png|jpg|gif)\Z/i}
    has_one_attached :pic
end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
	belongs_to :item
	belongs_to :cart
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
	belongs_to :item
	belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :join_table_order_items
	has_many :items, through: :join_table_order_items
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


	after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  has_many :items, through: :cart
  has_many :orders
  has_one :cart

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_paramters, if: :devise_controller?

  protected
    def configure_permitted_paramters

        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :description, :age])

        devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :description, :age,
        :email, :password])

    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_cart, only: [:show]
    before_action :authenticate_user!, exept: [:index, :show]
 
  def index
    @carts = Cart.all
  end

  def show
    @cart = Cart.find(params[:id])
    def sum
      sum = 0
        for i in (0..@cart.join_table_cart_items.length-1)
          sum = sum + @cart.join_table_cart_items[i].item.price
        end
      return sum 
    end
    @sum = sum
  end

  def new
  end

  def create
    @item = Item.find(params[:item_id])
    @join_table_cart_items = @cart.join_table_cart_item.new(item: item)
  end

  def update
  end

  def destroy
  end

  def edit
  
  end
  
  private

    def set_cart
      @cart = Cart.find_by(id: session[:cart_id]) || Cart.create
        session[:cart_id] ||= @cart.id
    end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

   def index
    @items = Item.all
    puts @items
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "Description ajouté! maintenant upload votre cat_pic"
      redirect_to new_item_pic_path(@item.id)
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  def edit
  end

  private
    def item_params
      params.require(:item).permit(
                  :title, 
                  :description,
                  :price)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def show
    
  end

  def new
  end

  def create

      # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to root_path
      

  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  def new
  end

  def create
    @item = Item.find(params[:item_id])
    @item.pic.attach(params[:pic])
    redirect_to item_path(@item.id)
  end

  def index
  end

  def show
  end

  def update
  end

  def destroy
  end

  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :is_admin?, only: [:index]
	def show
		 @user = User.find(params[:id])
	end

	def index
		@order = Order.all
	end

	private
	def is_admin?
		if current_user.admin == true
			return true
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_admin.html.erb
<% if current_user && current_user.admin %>

<h1>ESPACE ADMINISTRATEUR</h1>
<ul>
	<li><%= link_to "Dashboard", users_path %></li>
</ul>


<%end%>

app/views/layouts/_authentication.html.erb
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "home", items_path %>
    </li>
    <li>
      <%= link_to "profil", current_user %>
    </li>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>
    
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- TITRE -->
    <title> CATTO
    </title>
    <!-- Important pour medias queries -->
    <meta content="initial-scale=1.0, width=device-width" name="viewport">
    <!-- Police de Caractère -->
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <!-- FEUILLES DE STYLE -->
    <link rel="stylesheet" href="assets/css/styles.css">
    <!-- scrollmagic -->

<body>


<!--NEW METHODES FOR PAGES-->
    <style>
    .a{
        height: 243px;
        width: 195px;
    }
    </style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <div><%= link_to"HOME", root_path %></div>
         
  </head>

  <body>
    <%= render "layouts/admin" %>
    <%= render "layouts/authentication" %>
 
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
     
    <%= yield %>

  </body>
</html>